defmodule NbRoutes.TypeGenerator do
  @moduledoc """
  Generates TypeScript type definitions for route helpers.
  """

  alias NbRoutes.{Configuration, Route}

  @doc """
  Generates TypeScript definitions for the given routes.

  ## Examples

      iex> routes = [%NbRoutes.Route{name: "user_path", ...}]
      iex> NbRoutes.TypeGenerator.generate(routes, %NbRoutes.Configuration{})
      "export const user_path: ..."

  """
  def generate(routes, %Configuration{} = config) do
    [
      generate_header(),
      "",
      generate_types(),
      "",
      generate_route_types(routes, config),
      "",
      generate_config_types()
    ]
    |> Enum.join("\n")
  end

  # Private functions

  defp generate_header do
    """
    /**
     * Generated TypeScript definitions for route helpers
     * Generated by NbRoutes
     *
     * @warning DO NOT EDIT - This file is auto-generated
     */
    """
    |> String.trim()
  end

  defp generate_types do
    """
    /**
     * Valid route parameter types
     */
    export type RouteParameter = string | number | boolean;

    /**
     * Options that can be passed to route helpers
     */
    export interface RouteOptions {
      /** URL anchor (hash) */
      anchor?: string;
      /** Add trailing slash to the path */
      trailing_slash?: boolean;
      /** Additional query string parameters */
      [key: string]: RouteParameter | undefined;
    }

    /**
     * Default URL options for absolute URLs
     */
    export interface DefaultUrlOptions {
      /** URL scheme (http, https) */
      scheme?: string;
      /** Host name */
      host?: string;
      /** Port number */
      port?: number;
    }

    /**
     * Configuration options for route generation
     */
    export interface RouteConfig {
      defaultUrlOptions?: DefaultUrlOptions;
      trailingSlash?: boolean;
    }

    /**
     * Route helper function with introspection methods
     */
    export interface RouteHelper<TParams extends any[] = any[]> {
      (...args: TParams): string;
      requiredParams(): string[];
      toString(): string;
    }
    """
    |> String.trim()
  end

  defp generate_route_types(routes, config) do
    routes
    |> Enum.map(&generate_route_type(&1, config))
    |> Enum.join("\n\n")
  end

  defp generate_route_type(%Route{} = route, _config) do
    type_signature = generate_type_signature(route)

    """
    /**
     * #{route.verb} #{route.path}
     *
     * @example
     * #{generate_type_example(route)}
     */
    export const #{route.name}: RouteHelper<[#{type_signature}]>;
    """
    |> String.trim()
  end

  defp generate_type_signature(%Route{required_params: [], optional_params: []}) do
    "options?: RouteOptions"
  end

  defp generate_type_signature(%Route{required_params: required, optional_params: []}) do
    required_types = Enum.map_join(required, ", ", fn _ -> "RouteParameter" end)
    "#{required_types}, options?: RouteOptions"
  end

  defp generate_type_signature(%Route{required_params: required, optional_params: _optional}) do
    # When there are optional params, they're part of the options object
    if Enum.empty?(required) do
      "options?: RouteOptions"
    else
      required_types = Enum.map_join(required, ", ", fn _ -> "RouteParameter" end)
      "#{required_types}, options?: RouteOptions"
    end
  end

  defp generate_type_example(%Route{required_params: []} = route) do
    "#{route.name}()"
  end

  defp generate_type_example(%Route{required_params: params} = route) do
    example_values = Enum.map(params, fn _ -> "1" end)
    "#{route.name}(#{Enum.join(example_values, ", ")})"
  end

  defp generate_config_types do
    """
    /**
     * Configure route generation options
     *
     * @param options - Configuration options
     *
     * @example
     * configure({
     *   defaultUrlOptions: {
     *     scheme: 'https',
     *     host: 'example.com'
     *   }
     * });
     */
    export function configure(options: RouteConfig): void;

    /**
     * Get current configuration
     *
     * @returns Current route configuration
     */
    export function config(): RouteConfig;
    """
    |> String.trim()
  end
end
