defmodule NbRoutes.TypeGenerator do
  @moduledoc """
  Generates TypeScript type definitions for route helpers.
  """

  alias NbRoutes.{Configuration, Route}

  @doc """
  Generates TypeScript definitions for the given routes.

  ## Examples

      iex> routes = [%NbRoutes.Route{name: "user_path", ...}]
      iex> NbRoutes.TypeGenerator.generate(routes, %NbRoutes.Configuration{})
      "export const user_path: ..."

  """
  def generate(routes, %Configuration{} = config) do
    [
      generate_header(),
      "",
      generate_types(config),
      "",
      generate_route_types(routes, config),
      "",
      generate_config_types(config)
    ]
    |> Enum.join("\n")
  end

  # Private functions

  defp generate_header do
    """
    /**
     * Generated TypeScript definitions for route helpers
     * Generated by NbRoutes
     *
     * @warning DO NOT EDIT - This file is auto-generated
     */
    """
    |> String.trim()
  end

  defp generate_types(%Configuration{variant: :rich, with_forms: true}) do
    """
    /**
     * Valid route parameter types
     */
    export type RouteParameter = string | number | boolean;

    /**
     * Result returned by rich route helpers
     */
    export interface RouteResult {
      /** Generated URL */
      url: string;
      /** HTTP method */
      method: 'get' | 'post' | 'patch' | 'put' | 'delete' | 'head' | 'options';
    }

    /**
     * Attributes for HTML form elements
     */
    export interface FormAttributes {
      /** Form action URL (with method spoofing via _method parameter if needed) */
      action: string;
      /** Form method (always 'get' or 'post') */
      method: 'get' | 'post';
    }

    /**
     * Options that can be passed to route helpers
     */
    export interface RouteOptions {
      /** URL anchor (hash) */
      anchor?: string;
      /** Query string parameters to append */
      query?: Record<string, RouteParameter>;
      /** Query string parameters to merge with existing query */
      mergeQuery?: Record<string, RouteParameter | null | undefined>;
    }

    /**
     * Default URL options for absolute URLs
     */
    export interface DefaultUrlOptions {
      /** URL scheme (http, https) */
      scheme?: string;
      /** Host name */
      host?: string;
      /** Port number */
      port?: number;
    }

    /**
     * Configuration options for route generation
     */
    export interface RouteConfig {
      defaultUrlOptions?: DefaultUrlOptions;
      trailingSlash?: boolean;
    }

    /**
     * Route helper function with method and form variants
     */
    export interface RouteHelperWithForm<TParams extends any[] = any[]> {
      /** Main helper - returns RouteResult with url and method */
      (...args: TParams): RouteResult;
      /** GET method variant */
      get(...args: TParams): RouteResult;
      /** HEAD method variant */
      head(...args: TParams): RouteResult;
      /** URL-only variant - returns just the URL string */
      url(...args: TParams): string;
      /** Form helper - returns FormAttributes for use with HTML forms */
      form: {
        /** Main form helper - uses the route's original HTTP method */
        (...args: TParams): FormAttributes;
        /** PATCH form variant */
        patch(...args: TParams): FormAttributes;
        /** PUT form variant */
        put(...args: TParams): FormAttributes;
        /** DELETE form variant */
        delete(...args: TParams): FormAttributes;
      };
    }

    /**
     * Route helper function with method variants (no form support)
     */
    export interface RouteHelper<TParams extends any[] = any[]> {
      /** Main helper - returns RouteResult with url and method */
      (...args: TParams): RouteResult;
      /** GET method variant */
      get(...args: TParams): RouteResult;
      /** HEAD method variant */
      head(...args: TParams): RouteResult;
      /** URL-only variant - returns just the URL string */
      url(...args: TParams): string;
    }
    """
    |> String.trim()
  end

  defp generate_types(%Configuration{variant: :rich}) do
    """
    /**
     * Valid route parameter types
     */
    export type RouteParameter = string | number | boolean;

    /**
     * Result returned by rich route helpers
     */
    export interface RouteResult {
      /** Generated URL */
      url: string;
      /** HTTP method */
      method: 'get' | 'post' | 'patch' | 'put' | 'delete' | 'head' | 'options';
    }

    /**
     * Options that can be passed to route helpers
     */
    export interface RouteOptions {
      /** URL anchor (hash) */
      anchor?: string;
      /** Query string parameters to append */
      query?: Record<string, RouteParameter>;
      /** Query string parameters to merge with existing query */
      mergeQuery?: Record<string, RouteParameter | null | undefined>;
    }

    /**
     * Default URL options for absolute URLs
     */
    export interface DefaultUrlOptions {
      /** URL scheme (http, https) */
      scheme?: string;
      /** Host name */
      host?: string;
      /** Port number */
      port?: number;
    }

    /**
     * Configuration options for route generation
     */
    export interface RouteConfig {
      defaultUrlOptions?: DefaultUrlOptions;
      trailingSlash?: boolean;
    }

    /**
     * Route helper function with method variants
     */
    export interface RouteHelper<TParams extends any[] = any[]> {
      /** Main helper - returns RouteResult with url and method */
      (...args: TParams): RouteResult;
      /** GET method variant */
      get(...args: TParams): RouteResult;
      /** HEAD method variant */
      head(...args: TParams): RouteResult;
      /** URL-only variant - returns just the URL string */
      url(...args: TParams): string;
    }
    """
    |> String.trim()
  end

  defp generate_types(%Configuration{variant: :simple}) do
    """
    /**
     * Valid route parameter types
     */
    export type RouteParameter = string | number | boolean;

    /**
     * Options that can be passed to route helpers
     */
    export interface RouteOptions {
      /** URL anchor (hash) */
      anchor?: string;
      /** Add trailing slash to the path */
      trailing_slash?: boolean;
      /** Additional query string parameters */
      [key: string]: RouteParameter | undefined;
    }

    /**
     * Default URL options for absolute URLs
     */
    export interface DefaultUrlOptions {
      /** URL scheme (http, https) */
      scheme?: string;
      /** Host name */
      host?: string;
      /** Port number */
      port?: number;
    }

    /**
     * Configuration options for route generation
     */
    export interface RouteConfig {
      defaultUrlOptions?: DefaultUrlOptions;
      trailingSlash?: boolean;
    }

    /**
     * Route helper function with introspection methods
     */
    export interface RouteHelper<TParams extends any[] = any[]> {
      (...args: TParams): string;
      requiredParams(): string[];
      toString(): string;
    }
    """
    |> String.trim()
  end

  defp generate_route_types(routes, config) do
    routes
    |> Enum.map(&generate_route_type(&1, config))
    |> Enum.join("\n\n")
  end

  defp generate_route_type(%Route{} = route, config) do
    type_signature = generate_type_signature(route)
    helper_interface = get_helper_interface(route, config)

    """
    /**
     * #{route.verb} #{route.path}
     *
     * @example
     * #{generate_type_example(route)}
     */
    export const #{route.name}: #{helper_interface}<[#{type_signature}]>;
    """
    |> String.trim()
  end

  defp get_helper_interface(%Route{verb: verb}, %Configuration{with_forms: true, variant: :rich}) do
    method = verb |> to_string() |> String.downcase()

    if method in ["post", "patch", "put", "delete"] do
      "RouteHelperWithForm"
    else
      "RouteHelper"
    end
  end

  defp get_helper_interface(_route, _config), do: "RouteHelper"

  defp generate_type_signature(%Route{required_params: [], optional_params: []}) do
    "options?: RouteOptions"
  end

  defp generate_type_signature(%Route{required_params: required, optional_params: []}) do
    required_types = Enum.map_join(required, ", ", fn _ -> "RouteParameter" end)
    "#{required_types}, options?: RouteOptions"
  end

  defp generate_type_signature(%Route{required_params: required, optional_params: _optional}) do
    # When there are optional params, they're part of the options object
    if Enum.empty?(required) do
      "options?: RouteOptions"
    else
      required_types = Enum.map_join(required, ", ", fn _ -> "RouteParameter" end)
      "#{required_types}, options?: RouteOptions"
    end
  end

  defp generate_type_example(%Route{required_params: []} = route) do
    "#{route.name}()"
  end

  defp generate_type_example(%Route{required_params: params} = route) do
    example_values = Enum.map(params, fn _ -> "1" end)
    "#{route.name}(#{Enum.join(example_values, ", ")})"
  end

  defp generate_config_types(%Configuration{variant: :rich}) do
    """
    /**
     * Configure route generation options
     *
     * @param options - Configuration options
     *
     * @example
     * configure({
     *   defaultUrlOptions: {
     *     scheme: 'https',
     *     host: 'example.com'
     *   }
     * });
     */
    export function configure(options: RouteConfig): void;

    /**
     * Get current configuration
     *
     * @returns Current route configuration
     */
    export function config(): RouteConfig;

    /**
     * Build URL from pattern and params (low-level helper)
     *
     * @param pattern - URL pattern with :param placeholders (e.g., "/users/:id")
     * @param params - Parameter values (e.g., { id: 1 })
     * @param options - URL options (query, mergeQuery, anchor)
     * @returns Built URL string
     *
     * @example
     * _buildUrl("/users/:id", { id: 123 }, { query: { filter: "active" } })
     * // => "/users/123?filter=active"
     */
    export function _buildUrl(
      pattern: string,
      params?: Record<string, RouteParameter>,
      options?: RouteOptions
    ): string;
    """
    |> String.trim()
  end

  defp generate_config_types(%Configuration{variant: :simple}) do
    """
    /**
     * Configure route generation options
     *
     * @param options - Configuration options
     *
     * @example
     * configure({
     *   defaultUrlOptions: {
     *     scheme: 'https',
     *     host: 'example.com'
     *   }
     * });
     */
    export function configure(options: RouteConfig): void;

    /**
     * Get current configuration
     *
     * @returns Current route configuration
     */
    export function config(): RouteConfig;
    """
    |> String.trim()
  end
end
